# site settings
title: Nicolas Hachet
description: CTO / Directeur Technique
baseurl: ""
url: https://www.nicolashachet.com
taglong: Directeur Technique à Nantes
tagshort: Directeur Technique
ga: G-RWKL2Z7WQ7

# author settings
author:
  name: Nicolas Hachet
  email: contact@nicolashachet.com
  website: www.nicolashachet.com
photo: assets/files/nicolas-hachet.png
address: Nantes, France
phone:

# social media links
social:
  github: nicolashachet
  linkedin: nicolas-hachet

# build settings
permalink: /:categories/:title # none # https://jekyllrb.com/docs/permalinks/#permalink-style-examples
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
  - .idea/
  - backup/

# Plugins
plugins:
  - jekyll-sitemap
